'use client'
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Rightbar from "./components/Rightbar/Rightbar";
import { AnimatePresence,motion } from "framer-motion";
import { usePathname } from "next/navigation"

// export const metadata = {
//   title: "Personal Website",
//   description: "Generated by create next app",
// };



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



const pageTransition = {
  initial:{
    y:1000,
    
  },
  animate:{
    
    y:0,
    
  },
  exit:{
    
    y:-1000,
  },
};

export default function RootLayout({ children }) {

  

  return (
    <html lang="en">
      <body >
        

       

        <Navbar />
        <Rightbar />
        <AnimatePresence>
          <motion.div
          key={typeof window!== "undefined" ? window.location.pathname:''}
          initial="initial"
          animate="animate"
          exit="exit"
          variants={pageTransition}
          transition={{duration:1}}
          
          >
            
          {children}

          </motion.div>
        </AnimatePresence>

      </body>
    </html>
  );
}
