
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import Rightbar from "./components/Rightbar/Rightbar";
import { AnimatePresence,motion } from "framer-motion";

export const metadata = {
  title: "Personal Website",
  description: "Generated by create next app",
};



const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});



const pageTransition = {
  initial:{
    x:100,
    opacity:0,
  },
  animate:{
    opacity:1,
    x:0,
    
  },
  exit:{
    opacity:0,
    x:-100,
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <Navbar />
        <Rightbar />

        {/* <AnimatePresence>
          <motion.div
          key={typeof window!== "undefined" ? window.location.pathname:''}
          initial="initial"
          animate="animate"
          exit="exit"
          variable={pageTransition}
          transition={{duration:0.5}}
          > */}

          {children}

          {/* </motion.div>
        </AnimatePresence> */}

      </body>
    </html>
  );
}
